name:           network-lightning
version:        0.1.0.0
description:    API to c-lightning jsonrpc interface
homepage:       https://github.com/michaelsdunn1/network-lightning#readme
bug-reports:    https://github.com/michaelsdunn1/network-lightning/issues
author:         Michael Dunn <michaelsdunn1@gmail.com>
maintainer:     Michael Dunn <michaelsdunn1@gmail.com>
copyright:      2019 Michael Dunn <michaelsdunn1@gmail.com>
license:        MIT
license-file:   LICENSE
build-type:     Simple

extra-source-files:
    README.md

github: https://github.com/michaelsdunn1/network-lightning

library:
  source-dirs: src/lib/
  ghc-options: -Wall -fwarn-tabs -O2 -funbox-strict-fields

dependencies:
  - base                 >= 4.7  && < 5
  - aeson                >= 1.2  && < 1.4
  - aeson-casing         >= 0.1  && < 0.2
  - bytestring           >= 0.10 && < 0.11
  - containers           >= 0.5  && < 0.6
  - haskoin-core         >= 0.8  && < 0.9
  - network              >= 2.6  && < 2.7
  - text                 >= 1.2  && < 1.3
  - time                 >= 1.8  && < 1.9
  - transformers         >= 0.5  && < 0.6
  - unordered-containers >= 0.2  && < 0.3
  - vector               >= 0.12 && < 0.13

executables:
  network-lightning-example:
    main: example/Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -funbox-strict-fields
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - network-lightning
